# Config File for Sunlight app and related items
defaults: &defaults
  sunlight_api_url: "http://api.richmondsunlight.com/1.0/"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
